services:
  - type: web
    name: go-backend
    env: go
    buildCommand: go build -o app
    startCommand: ./app
    autoDeploy: true
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres
    rootDir: backend

  - type: static
    name: react-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://go-backend.onrender.com
    rootDir: frontend
